# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: D

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Dub tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        dc: [dmd-latest, ldc-latest, dmd-2.094.2, ldc-1.24.0, dmd-2.091.1]
        include:
          - { os: macOS-latest, dc: dmd-latest, arch: x86_64 }
          - { os: macOS-latest, dc: ldc-latest, arch: x86_64 }
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Install D compiler
      uses: dlang-community/setup-dlang@v2
      with:
          compiler: ${{ matrix.dc }}
    - name: Run tests
      run: scripts/ci.sh
    - name: Upload codecov
      if: matrix.os == 'ubuntu-latest' && matrix.dc == 'dmd-latest'
      env:
        COVERAGE: true
      run: scripts/ci.sh
